EXPERIMENT:
  NAME: "dqn_dqn4_da_001_3"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
  TEACHER: "dqn3"
  STUDENT: "dqn4"
DA:
  LR: 0.001
  PROB: 0.3