EXPERIMENT:
  NAME: "dqn_dqn3_da_01_2"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_dqn_da"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn3"
DA:
  LR: 0.001
  PROB: 0.2