EXPERIMENT:
  NAME: "dqn_dqn5_da_breakout"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: False
  BAR: True
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn5"
DA:
  LR: 0.001
  PROB: 0.3