EXPERIMENT:
  NAME: "Breakout/DQN/DA, 0.01 lr, 0.2 prob"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_da_tests"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
DA:
  LR: 0.01
  PROB: 0.2