EXPERIMENT:
  NAME: "KD_Atari"
  TAG: "kd,atari"

DISTILLER:
  TYPE: "KD"
  TEACHER: "PongNoFrameskip-v4_Trainer"
  STUDENT: "CustomCNN"

ENV:
  ID: "PongNoFrameskip-v4"
  SEED: 123
  WRAPPERS: ["DefaultAtariWrappers"]

SOLVER:
  TOTAL_TIMESTEPS: 1e6
  LOG_INTERVAL: 10000
  EVAL_EPISODES: 5
  SAVE_PATH: "./checkpoints/kd_atari"

KD:
  ALPHA: 0.5
  TEMPERATURE: 2.0
