EXPERIMENT:
  NAME: "dqn_dqn_TEST"
  TAG: "breakout, dqn, PD"
  PROJECT: "policy_distillation_tests"
LOG:
  WANDB: False
  BAR: True
DISTILLER:
  TYPE: "DA"
  ENV: "BeamRiderNoFrameskip-v4"
  STUDENT: "dqn5"
# DATA:
  # INCREMENT_SIZE: 1000