EXPERIMENT:
  NAME: "dqn_dqn_TEST"
  TAG: "breakout, dqn, PD"
  PROJECT: "policy_distillation_tests"
LOG:
  WANDB: False
  BAR: True
  FINAL_EVAL_EPS: 10
DISTILLER:
  TYPE: "DA"
  ENV: "SpaceInvadersNoFrameskip-v4"
SOLVER:
  EPOCHS: 1
DATA:
  INCREMENT_SIZE: 1000