EXPERIMENT:
  NAME: "dqn_dqn4_pd_spaceinvaders"
  TAG: "breakout, dqn, PD"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "PD"
  STUDENT: "dqn4"
  ENV: "SpaceInvadersNoFrameskip-v4"