EXPERIMENT:
  NAME: "dqn_dqn5_da_spaceinvaders"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn5"
  ENV: "SpaceInvadersNoFrameskip-v4"