EXPERIMENT:
  NAME: "dqn_dqn4_da_0001_beamrider"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn4"
  ENV: "BeamRiderNoFrameskip-v4"
DA:
  LR: 0.0001
  PROB: 0.3
