EXPERIMENT:
  NAME: "dqn_dqn5_da_beamrider"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn5"
  ENV: "BeamRiderNoFrameskip-v4"
DA:
  LR: 0.001
  PROB: 0.3