EXPERIMENT:
  NAME: "dqn_dqn6_da_00001_beamrider"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn6"
  ENV: "BeamRiderNoFrameskip-v4"
DA:
  LR: 0.00001
  PROB: 0.3