EXPERIMENT:
  NAME: "dqn_dqn4_pd_pong"
  TAG: "breakout, dqn, PD"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
  EVAL_FREQ: 3
  EVAL_EPISODES: 50
DISTILLER:
  TYPE: "PD"
  STUDENT: "dqn4"
  ENV: "PongNoFrameskip-v4"