EXPERIMENT:
  NAME: "dqn_dqn4_da_0001_pong"
  TAG: "breakout, dqn, DA"
  PROJECT: "policy_distillation_small_dqn"
LOG:
  WANDB: True
  BAR: False
  EVAL_FREQ: 3
  EVAL_EPISODES: 50
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn4"
  ENV: "PongNoFrameskip-v4"
DA:
  LR: 0.0001
  PROB: 0.3
