EXPERIMENT:
  NAME: "dqn_dqn4_da_mspacman_5400_01"
  TAG: "mspacman, dqn, DA, 5400"
  PROJECT: "policy_distillation_less_data"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "DA"
  STUDENT: "dqn4"
  ENV: "MsPacmanNoFrameskip-v4"
DATA:
  INCREMENT: False
  MAX_CAPACITY: 5400
DA:
  LR: 0.1
