EXPERIMENT:
  NAME: "dqn_dqn4_pd_mspacman_54000"
  TAG: "mspacman, dqn, PD, 54000"
  PROJECT: "policy_distillation_less_data"
LOG:
  WANDB: True
  BAR: False
DISTILLER:
  TYPE: "PD"
  STUDENT: "dqn4"
  ENV: "MsPacmanNoFrameskip-v4"
DATA:
  INCREMENT: False
  MAX_CAPACITY: 54000
